<a href="https://colab.research.google.com/github/gotserena/data_viz_2022/blob/main/Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Data Strucuture (โครงสร้างข้อมูล)
การเก้บข้อมูลหลายๆตัวไว้ด้วยกันอย่างเป็นร
ะเบียบ

## list()
*   เก็บอะไรก็ได้
*   ลำดับในการเก็บ มีความสำศัญ



In [ ]:
list_a = [1,2,3,4,5,6] #square brackets

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_b = ['ab',2,3.14,list_a]#่เก็บข้อมูลชนิดหนึ่ง

In [ ]:
list_b

['ab', 2, 3, 14, [1, 2, 3, 4, 5, 6]]

## indexing การชี้สมาชิกใน list ด้วย เลขลำดับของ list

In [ ]:
list_a[3]

4

In [ ]:
list_b[3] 

14

In [ ]:
list_b[3][4]

5

In [ ]:
list_a[6] #เกินที่มีอยู่

IndexError: ignored

In [ ]:
list_a[-1]  #Index -1  เรียงจากหลังมา


6

In [ ]:
list_a[-4] # index -4 เป็นตัวที่4 นับจากหลัง


3

#การสร้าง list()


In [ ]:
list_x1 = [] #แบบที่ 1 
list_x2 = list() # แบบที่ 2

In [ ]:
print(list_x1)
print(list_x2)

[]
[]


#เพิ่มสมาชิกเข้าไปใน list ด้วย append()


In [ ]:
list_x1.append(2) #เพิ่มเลข 2 ลงใน list


In [ ]:
list_x1

[2, 2]

In [ ]:
list_x1.append(3) 
print(list_x1)

[2, 2, 3]


In [ ]:
list_x1[0]


2

#ลบสมาชิกใน list


In [ ]:
list_x2.append('ha')


In [ ]:
list_x2


['ha', 'ha']

In [ ]:
list_x1.pop() #ลบหลังสุด


3

In [ ]:
list_x1

[2, 2]

In [ ]:
list_x1.pop()
print(list_x1)

[2]


#len() ตรวจสอบจำนวนสมาชิก


In [ ]:
print(list_b)
print(len(list_b))

['ab', 2, 3.14, [1, 2, 3, 4, 5, 6]]
4


In [ ]:
len(list_a)


6

## Sting is a list of characters

In [ ]:
st_stat = 'Department of Statistics, Faculty of Science'


In [ ]:
st_stat[10]


' '

In [ ]:
len(st_stat)


44

-  `list[จุด เริ่มต้น (ทืบ) :จุดสุดท้าย (โปร่ง)]`
- `list[จุดเริ่มต้น:จุดสุดท้าย:step]`

In [ ]:
list_a

[1, 2, 3, 4, 5, 6]

In [ ]:
list_a[2]

3

# : colon

In [ ]:
list_a[:4] #เอาตัวก่อนหน้าตำแหน่งที่ 4

[1, 2, 3, 4]

In [ ]:
list_a[-3:] # colon เอา3 ตัวจากหลังมาหน้า

[4, 5, 6]

In [ ]:
list_a[1:4] # เริ่มจากตำแหน่ง 1(แต่ไม่เอาตำแหน่งที่1 ) ถึง 4

[2, 3, 4]

In [ ]:
list_a[:]

[1, 2, 3, 4, 5, 6]

# step


In [ ]:
list_c = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]

In [ ]:
list_c[:10:]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
list_c[:10:2] #เอาถึงตำแหน่ง 10 และห่างกันตำแหน่งที่ 2

[1, 3, 5, 7, 9]

In [ ]:
list_c[::-1]

[15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

# range()

In [ ]:
a= list(range(21))

In [ ]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [ ]:
range(21) #เพิ่มเลขจะได้เลข0-21

range(0, 21)

In [ ]:
list(range(1,21)) #กำหนดตั้งแต่ใส่เลข 1-21

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

###HW2 คำนวณเวลาเป็นวินาทีของเวลาต่อไปนี้โดยใช้คำสั่ง split() ช่วย (print ออกมาให้สวยงาม)
- 12:30:15
- 13:41:07
- 21:30:15
- 01:10:15

In [ ]:
# EX 01:02:03

a= (1*60*60) + (2*60)+(3)
print(f'01:02:03 แปลงเป็นวินาทีได้ {a} วินาที')

01:02:03 แปลงเป็นวินาทีได้ 3723 วินาที


In [ ]:
# ข้อ1 12:30:15
a = '12:30:15' 
a_1 = a.split(':') # แยกตัวแปรโดยแย่งตรงแบ่ง : 
ans1 = int(a_1[0])*60*60 + int(a_1[1])*60 + int(a_1[2]) # แปลงข้อมูลให้เป็น int + กัน
print(f'เวลา 12:30:15 แปลงเป็นวินาทีได้ {ans1} วินาที')

เวลา 12:30:15 แปลงเป็นวินาทีได้ 45015 วินาที


In [ ]:
# ข้อ2 13:41:07
a = '13:41:07' 
a_2 = a.split(':')   # แยกตัวแปรโดยแย่งตรงแบ่ง :
ans2 = int(a_2[0])*60*60 + int(a_2[1])*60 + int(a_2[2])    # แปลงข้อมูลให้เป็น int + กัน
print(f'เวลา13:41:07 แปลงเป็นวินาทีได้ {ans2} วินาที')

เวลา13:41:07 แปลงเป็นวินาทีได้ 49267 วินาที


In [ ]:
# ข้อ3 9:11:50
a = '9:11:50'
a_3 = a.split(':') # แยกตัวแปรโดยแย่งตรงแบ่ง :
ans3 = int(a_3[0])*60*60 + int(a_3[1])*60 + int(a_3[2])   # แปลงข้อมูลให้เป็น int + กัน
print(f'เวลา 9:11:50 แปลงเป็นวินาทีได้ {ans3} วินาที')

เวลา 9:11:50 แปลงเป็นวินาทีได้ 33110 วินาที


In [ ]:
# ข้อ4 21:30:15
a = '21:30:15'
a_4 = a.split(':') # แยกตัวแปรโดยแย่งตรงแบ่ง :
ans4 = int(a_4[0])*60*60 + int(a_4[1])*60 + int(a_4[2])   # แปลงข้อมูลให้เป็น int + กัน
print(f'เวลา 21:30:15 แปลงเป็นวินาทีได้ {ans4} วินาที')

เวลา 21:30:15 แปลงเป็นวินาทีได้ 77415 วินาที


In [ ]:
# ข้อ5 03:10:15
a = '03:10:15'
a_5 = a.split(':') # แยกตัวแปรโดยแย่งตรงแบ่ง :
ans5 = int(a_5[0])*60*60 + int(a_5[1])*60 + int(a_5[2]) # แปลงข้อมูลให้เป็น int + กัน
print(f'เวลา 03:10:15 แปลงเป็นวินาทีได้ {ans5} วินาที')

เวลา 03:10:15 แปลงเป็นวินาทีได้ 11415 วินาที


###Dictionary
- คล้าย list()
- index เป็นอะไรก็ได้ ไม่จำเป็นต้องเป็นตัวลำดับ
- ลำดับไม่มีความสำคัญ


### สร้าง Dictionary

### การชี้ สมาชิกใน DIctionary

In [5]:
dict_a = {1:'Happy','N':'New','2022':'Year'} # { } curly brackets

In [6]:
dict_a[1]

'Happy'

In [7]:
dict_a['N']

'New'

In [8]:
dict_a["2022"]

'Year'

In [9]:
dict_a.keys() #.keys() เรียกดูสมาชิกทั้งหมดว่ามีตัวแปรอะไรบ้าง

dict_keys([1, 'N', '2022'])

In [10]:
dict_a.values() # .values() บอกความหมายที่อยู่ใน dict

dict_values(['Happy', 'New', 'Year'])

### การเพิ่มสมาชิกลงไปใน DIctionary

In [12]:
dict_a[7] = 3.14

In [13]:
dict_a

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'New'}

In [14]:
dict_a["N"] = "NNNNEWWWW"

In [15]:
dict_a # เมื่อใช้ index ซ้ำมันค่าบันทึกค่าใหม่แทนที่ค่าเดิม

{1: 'Happy', '2022': 'Year', 7: 3.14, 'N': 'NNNNEWWWW'}

## Numpy Array

- เก็บได้แค่ตัวเลข
- อ้างอิงโดยใช้พิกัด (2มิติ ก็มองเป็น Matrix)

In [18]:
import numpy # ใช้code ของคนอื่นที่เขียนไว้

### 1D array

In [20]:
arr_a = numpy.array([1,2,3,4,5])

In [21]:
arr_a

array([1, 2, 3, 4, 5])

In [22]:
arr_a[0]

1

In [23]:
list_A = [5,6,7,8,9] # ใช้ list ได้เหมือนกัน
arr_b = numpy.array(list_A)
arr_b

array([5, 6, 7, 8, 9])

In [24]:
5 * arr_a # Matrix (scalar multiplication)

array([ 5, 10, 15, 20, 25])

In [25]:
5*list_A # list จะต่างกับ arr ตรงนี้

[5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9, 5, 6, 7, 8, 9]

In [26]:
arr_c = numpy.array([10,20,30,40,50])

In [27]:
print(arr_a)

[1 2 3 4 5]


In [28]:
arr_a + arr_c #matrix บวก matrix 

array([11, 22, 33, 44, 55])

In [29]:
arr_a.shape

(5,)

### 2D arrary

In [31]:
import numpy as np # import แต่เปลี่ยนชื่อให้มันสั้นสะดวกต่อการพิมพ์

In [32]:
arr2_z = np.array([[1,2,3],[4,5,6]])

In [33]:
arr2_z

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
arr2_z.shape

(2, 3)

### np.zeros()

In [35]:
arr2_3_5_0 =np.zeros((3,5))

In [36]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
arr2_3_5_0[1,2] = 9

In [38]:
arr2_3_5_0

array([[0., 0., 0., 0., 0.],
       [0., 0., 9., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
arr2_3_5_0[1,2]

9.0

In [40]:
print(list_A)# เปลี่ยน ค่าใน list()
list_A[-1] = 'christmas'
print(list_A)

[5, 6, 7, 8, 9]
[5, 6, 7, 8, 'christmas']


###  np.ones()

In [41]:
arr2_4_5_1 = np.ones((4,5))

In [42]:
arr2_4_5_1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
arr2_4_5_200 = 200*np.ones((4,5))

In [44]:
arr2_4_5_200

array([[200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.],
       [200., 200., 200., 200., 200.]])

### Matrix operations

#### การบวก ลบ matrix $M \pm N$ บวกลบตัวที่อยู่ตำแหน่งเดียวกัน

In [45]:
arr2_4_5_200 + arr2_3_5_0 # บวกลบกันไม่ได้ เพราะ ขนาดไม่เท่ากัน

ValueError: ignored

In [46]:
arr2_4_5_200 + arr2_4_5_1

array([[201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.],
       [201., 201., 201., 201., 201.]])

#### การคูณ matrix 
- $aM$  scalar คูณ Matrix (scalar คูณกระจายเข้าไปทุกตัวของ Matrix) 
- $M \times N$คูณ Matrix (แถวคูณหลัก)

$aM$

In [47]:
5 * arr_a

array([ 5, 10, 15, 20, 25])

$M \times N$
- (m,n) $\times$ (n,o) = (m,o)

In [48]:
mat_a = np.array([[2,3,5],[4,6,7]])
mat_b = np.array([[1,2,5],[2,4,-7]])
mat_c = np.array([[2,3,],[4,6],[7,9]])

In [49]:
mat_a

array([[2, 3, 5],
       [4, 6, 7]])

In [50]:
mat_b

array([[ 1,  2,  5],
       [ 2,  4, -7]])

In [51]:
mat_c

array([[2, 3],
       [4, 6],
       [7, 9]])

axc, bxc

In [52]:
np.dot(mat_a,mat_c)

array([[ 51,  69],
       [ 81, 111]])

In [53]:
np.dot(mat_b,mat_c)

array([[ 45,  60],
       [-29, -33]])

cxa, cxb

In [54]:
np.dot(mat_c,mat_a)

array([[16, 24, 31],
       [32, 48, 62],
       [50, 75, 98]])

In [55]:
np.dot(mat_c,mat_b)

array([[  8,  16, -11],
       [ 16,  32, -22],
       [ 25,  50, -28]])

In [56]:
mat_a * mat_b # คูณตัวตำแหน่งเดียวกัน ใช้ไม่ได้

array([[  2,   6,  25],
       [  8,  24, -49]])

In [57]:
mat_x = np.dot(mat_c,mat_b)
print(mat_x)

[[  8  16 -11]
 [ 16  32 -22]
 [ 25  50 -28]]


### Matrix Slicing

In [58]:
mat_x[:2, :2]

array([[ 8, 16],
       [16, 32]])

##HW 3 

1. สร้าง array ที่เป็นรูปต้น chrismas
2. slice เลข 1 ออกมาจาก array HW3

In [59]:
HW3 = np.zeros((10,10))
HW3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [60]:
HW3[::4,2] = 1
HW3[::4,4] = 1
HW3[::4,6] = 1
HW3[::4,8] = 1
HW3

array([[0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

## ข้อ 1 

In [90]:
chris=1*np.ones((18,15))
chris[2:,7:8] = 9
chris[3:,6:9] = 9
chris[4,5:10] = 9
chris[5,4:11] = 9
chris[6,3:12] = 9
chris[7,6:9] = 9
chris[8,5:10] = 9
chris[9,4:11] = 9
chris[10,3:12] = 9
chris[11,2:13] = 9
chris[12,5:10] = 9
chris[13,3:12] = 9
chris[14,2:13] = 9
chris[15,1:14] = 9
chris[16,7:8] = 9
print(chris)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 9. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 9. 9. 9. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 9. 9. 9. 9. 9. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 9. 9. 9. 9. 9. 9. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 9. 9. 9. 9. 9. 9. 9. 9. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 9. 9. 9. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 9. 9. 9. 9. 9. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 9. 9. 9. 9. 9. 9. 9. 1. 1. 1. 1.]
 [1. 1. 1. 9. 9. 9. 9. 9. 9. 9. 9. 9. 1. 1. 1.]
 [1. 1. 9. 9. 9. 9. 9. 9. 9. 9. 9. 9. 9. 1. 1.]
 [1. 1. 1. 1. 1. 9. 9. 9. 9. 9. 1. 1. 1. 1. 1.]
 [1. 1. 1. 9. 9. 9. 9. 9. 9. 9. 9. 9. 1. 1. 1.]
 [1. 1. 9. 9. 9. 9. 9. 9. 9. 9. 9. 9. 9. 1. 1.]
 [1. 9. 9. 9. 9. 9. 9. 9. 9. 9. 9. 9. 9. 9. 1.]
 [1. 1. 1. 1. 1. 1. 9. 9. 9. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 9. 9. 9. 1. 1. 1. 1. 1. 1.]]
